from harness_aibom.collectors.ollama import discover_models, enrich_model_with_show_info
from harness_aibom.model import Component

# Ollama's own real, documented example response for POST /api/show
# (github.com/ollama/ollama/blob/main/docs/api.md, fetched directly
# during development -- see ollama.py's module docstring). Not verified
# against a live Ollama server in this sandbox (none was available) --
# these tests confirm this module's parsing against the real, published
# shape, never a guessed one.
REAL_SHOW_RESPONSE_EXAMPLE = {
    "modelfile": "# Modelfile generated by \"ollama show\"\n...",
    "parameters": "num_keep                       24\nstop                           \"<|start_header_id|>\"",
    "template": "{{ if .System }}<|start_header_id|>system<|end_header_id|>\n\n{{ .System }}<|eot_id|>{{ end }}",
    "details": {
        "parent_model": "",
        "format": "gguf",
        "family": "llama",
        "families": ["llama"],
        "parameter_size": "8.0B",
        "quantization_level": "Q4_0",
    },
    "model_info": {
        "general.architecture": "llama",
        "general.file_type": 2,
        "general.parameter_count": 8030261248,
        "llama.attention.head_count": 32,
    },
    "capabilities": ["completion", "vision"],
}


def test_discover_models_basic_fields():
    def fetch(url):
        assert url.endswith("/api/tags")
        return {"models": [{"name": "qwen3:8b", "digest": "abc123", "size": 100}]}

    [model] = discover_models("http://127.0.0.1:11434", fetch=fetch, show_fetch=None)
    assert model.name == "qwen3:8b"
    assert model.properties["digest"] == "abc123"


def test_model_digest_is_tagged_observed_when_present():
    # v0.9.0: digest is taken verbatim from Ollama's own manifest --
    # a real, directly observed fact, tagged so a reader can contrast it
    # with a genuinely inferred one elsewhere in the document (skills.py).
    def fetch(url):
        return {"models": [{"name": "qwen3:8b", "digest": "abc123"}]}

    [model] = discover_models("http://127.0.0.1:11434", fetch=fetch, show_fetch=None)
    assert model.properties["digestConfidence"] == "observed"


def test_model_with_no_digest_gets_no_confidence_tag_fabricated():
    def fetch(url):
        return {"models": [{"name": "qwen3:8b"}]}  # no digest at all

    [model] = discover_models("http://127.0.0.1:11434", fetch=fetch, show_fetch=None)
    assert "digest" not in model.properties
    assert "digestConfidence" not in model.properties


def test_unreachable_ollama_returns_no_models_not_a_crash():
    def fetch(url):
        raise ConnectionError("refused")

    assert discover_models("http://127.0.0.1:11434", fetch=fetch) == []


# ---- v0.9.0: /api/show enrichment (tokenizer/prompt-template metadata) --


def test_enrich_reads_real_documented_fields():
    comp = Component(component_class="model", name="llava:latest")
    added = enrich_model_with_show_info(
        comp, "http://127.0.0.1:11434", "llava:latest",
        show_fetch=lambda base_url, name: REAL_SHOW_RESPONSE_EXAMPLE,
    )
    assert added is True
    assert "start_header_id" in comp.properties["promptTemplate"]
    assert "num_keep" in comp.properties["declaredParameters"]
    assert comp.properties["capabilities"] == "completion,vision"
    assert comp.properties["modelfileFormat"] == "gguf"
    assert comp.properties["architecture"] == "llama"
    # parent_model is "" in the real example -- empty, not a real fact to record.
    assert "parentModel" not in comp.properties
    # architecture-specific model_info keys are deliberately never read.
    assert "llama.attention.head_count" not in str(comp.properties)


def test_enrich_records_a_real_parent_model_when_present():
    comp = Component(component_class="model", name="my-custom-model")
    response = dict(
        REAL_SHOW_RESPONSE_EXAMPLE,
        details=dict(REAL_SHOW_RESPONSE_EXAMPLE["details"], parent_model="llama3.1:8b"),
    )
    enrich_model_with_show_info(comp, "http://127.0.0.1:11434", "my-custom-model", show_fetch=lambda b, n: response)
    assert comp.properties["parentModel"] == "llama3.1:8b"


def test_enrich_returns_false_and_sets_nothing_on_network_failure():
    comp = Component(component_class="model", name="qwen3:8b")

    def boom(base_url, name):
        raise ConnectionError("Ollama not reachable")

    added = enrich_model_with_show_info(comp, "http://127.0.0.1:11434", "qwen3:8b", show_fetch=boom)
    assert added is False
    assert comp.properties == {}


def test_enrich_tolerates_an_older_ollama_with_an_unexpected_shape():
    comp = Component(component_class="model", name="qwen3:8b")
    # An endpoint that exists but returns something this module doesn't
    # recognize (e.g. a 200 with an empty object, or a non-dict body) --
    # never a crash, never a fabricated field.
    added = enrich_model_with_show_info(comp, "http://127.0.0.1:11434", "qwen3:8b", show_fetch=lambda b, n: {})
    assert added is False
    added2 = enrich_model_with_show_info(
        comp, "http://127.0.0.1:11434", "qwen3:8b", show_fetch=lambda b, n: "not-a-dict"
    )
    assert added2 is False


def test_discover_models_wires_show_fetch_per_model():
    def fetch(url):
        return {"models": [{"name": "llava:latest", "digest": "abc"}]}

    def show_fetch(base_url, name):
        assert name == "llava:latest"
        return REAL_SHOW_RESPONSE_EXAMPLE

    [model] = discover_models("http://127.0.0.1:11434", fetch=fetch, show_fetch=show_fetch)
    assert model.properties["architecture"] == "llama"


def test_discover_models_with_show_fetch_none_skips_enrichment_entirely():
    def fetch(url):
        return {"models": [{"name": "llava:latest", "digest": "abc"}]}

    [model] = discover_models("http://127.0.0.1:11434", fetch=fetch, show_fetch=None)
    assert "promptTemplate" not in model.properties


def test_discover_models_one_models_show_failure_does_not_drop_the_model():
    def fetch(url):
        return {"models": [{"name": "a", "digest": "x"}, {"name": "b", "digest": "y"}]}

    def show_fetch(base_url, name):
        if name == "a":
            raise TimeoutError("no response")
        return REAL_SHOW_RESPONSE_EXAMPLE

    models = discover_models("http://127.0.0.1:11434", fetch=fetch, show_fetch=show_fetch)
    by_name = {m.name: m for m in models}
    assert "promptTemplate" not in by_name["a"].properties
    assert by_name["b"].properties["architecture"] == "llama"
